### ISSUE TITLE
Error running the generator script

### ISSUE THREAD

**Issue by boggye** [oyvindberg/typo#35]
Script:

```
//> using dep "com.olvind.typo::typo:0.3.0"
//> using dep "com.olvind.typo::typo-dsl-doobie:0.3.0"
//> using scala "3.3.1"

import typo.*

// adapt to your instance and credentials
implicit val c: java.sql.Connection =
  java.sql.DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres?user=postgres&password=***")

val options = Options(
  // customize package name for generated code
  pkg = "com.prx.db",
  // pick your database library
  dbLib = Some(DbLibName.Doobie),
  jsonLibs = Nil,
  // many more possibilities for customization here
  // ...
)

// current folder, where you run the script from
val location = java.nio.file.Path.of(sys.props("user.dir"))

// destination folder. All files in this dir will be overwritten!
val targetDir = location.resolve("generator")

// where typo will look for sql files
val scriptsFolder = location.resolve("sql")

generateFromDb(options, scriptsPaths = List(scriptsFolder))
  .overwriteFolder(folder = targetDir)

```

The error I've got is:

```
typo: fetched tableConstraints from PG in 192ms
typo: fetched keyColumnUsage from PG in 9ms
typo: fetched referentialConstraints from PG in 25ms
typo: fetched pgEnums from PG in 5ms
typo: fetched tables from PG in 49ms
typo: fetched columns from PG in 258ms
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: IN could not convert type character to "char"
  Position: 650
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
        at anorm.Sql.resultSet$$anonfun$1$$anonfun$1(Anorm.scala:97)
        at resource.DefaultManagedResource.open(AbstractManagedResource.scala:107)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:84)
        at resource.ManagedResourceOperations$$anon$1.$anonfun$acquireFor$1(ManagedResourceOperations.scala:47)
        at resource.AbstractManagedResource.$anonfun$acquireFor$1(AbstractManagedResource.scala:85)
        at scala.util.control.Exception$Catch.$anonfun$either$1(Exception.scala:251)
        at scala.util.control.Exception$Catch.apply(Exception.scala:227)
        at scala.util.control.Exception$Catch.either(Exception.scala:251)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:85)
        at resource.ManagedResourceOperations$$anon$1.acquireFor(ManagedResourceOperations.scala:47)
        at resource.DeferredExtractableManagedResource.acquireFor(AbstractManagedResource.scala:25)
        at resource.ManagedResourceOperations.apply(ManagedResourceOperations.scala:31)
        at resource.ManagedResourceOperations.apply$(ManagedResourceOperations.scala:31)
        at resource.DeferredExtractableManagedResource.apply(AbstractManagedResource.scala:22)
        at resource.ManagedResourceOperations.acquireAndGet(ManagedResourceOperations.scala:29)
        at resource.ManagedResourceOperations.acquireAndGet$(ManagedResourceOperations.scala:29)
        at resource.DeferredExtractableManagedResource.acquireAndGet(AbstractManagedResource.scala:22)
        at anorm.Sql$.asTry$$anonfun$1(Anorm.scala:263)
        at scala.util.Try$.apply(Try.scala:210)
        at anorm.Sql$.asTry(Anorm.scala:263)
        at anorm.WithResult.asTry(SqlResult.scala:215)
        at anorm.WithResult.asTry$(SqlResult.scala:47)
        at anorm.SimpleSql.asTry(SimpleSql.scala:6)
        at anorm.WithResult.as(SqlResult.scala:205)
        at anorm.WithResult.as$(SqlResult.scala:47)
        at anorm.SimpleSql.as(SimpleSql.scala:6)
        at typo.generated.custom.view_find_all.ViewFindAllSqlRepoImpl$.apply(ViewFindAllSqlRepoImpl.scala:33)
        at typo.MetaDb$Input$.fromDb$$anonfun$7(MetaDb.scala:57)
        at typo.MetaDb$Input$.timed$1(MetaDb.scala:44)
        at typo.MetaDb$Input$.fromDb(MetaDb.scala:57)
        at typo.MetaDb$.fromDb(MetaDb.scala:66)
        at typo.generateFromDb$.apply(generateFromDb.scala:12)
        at GenDb$_.<init>(GenDb.sc:30)
        at GenDb_sc$.script$lzyINIT1(GenDb.sc:47)
        at GenDb_sc$.script(GenDb.sc:47)
        at GenDb_sc$.main(GenDb.sc:51)
        at GenDb_sc.main(GenDb.sc)
```

It would have been very nice if it showed more information about the current context.

**Comment by boggye** [comment]
This query fails:

```
SELECT nc.oid                                        as table_oid,
                   nc.nspname::information_schema.sql_identifier AS table_schema,
                   c.relname::information_schema.sql_identifier  AS table_name,
                   c.relkind,
                   CASE
                       WHEN pg_has_role(c.relowner, 'USAGE'::text) THEN pg_get_viewdef(c.oid)
                       ELSE NULL::text
                       END::information_schema.character_data    AS view_definition
            FROM pg_namespace nc,
                 pg_class c
            WHERE c.relnamespace = nc.oid
              AND c.relkind in ('m'::"char", 'v'::char)
            order by 1, 2, 3
```
ERROR:  IN could not convert type character to "char"
LINE 12:               AND c.relkind in ('m'::"char", 'v'::char)

I am executing it against a postgresql 12 database.

**Comment by boggye** [comment]
This one works:
```sql
SELECT nc.oid                                        as table_oid,
                   nc.nspname::information_schema.sql_identifier AS table_schema,
                   c.relname::information_schema.sql_identifier  AS table_name,
                   c.relkind,
                   CASE
                       WHEN pg_has_role(c.relowner, 'USAGE'::text) THEN pg_get_viewdef(c.oid)
                       ELSE NULL::text
                       END::information_schema.character_data    AS view_definition
            FROM pg_namespace nc,
                 pg_class c
            WHERE c.relnamespace = nc.oid
              AND c.relkind in ('m'::"char", 'v'::"char")
            order by 1, 2, 3
```

I added double-quotes: `'v'::"char"`

**Comment by oyvindberg** [comment]
Thanks! I haven't tested it against anything older than 14.

**Comment by boggye** [comment]
Are you going to "fix" the query so it's going to work with older versions of the database?
Thanks

**Comment by boggye** [comment]
I can do a PR if you want

**Comment by oyvindberg** [comment]
Absolutely, let's fix it! If it's easy for you to update the sql file, rerun bleep generate-sources and so feel free to give it a shot, if not I can fix it tonight I think.

I'm not sure if the contributing docs are up to par, but you would be a fine guinea pig for that

**Comment by boggye** [comment]
It would be great if you can fix it (whenever you have time).

**Comment by boggye** [comment]
Thank you!
